version: '2'
services:
    compte-app:
        image: compte
        external_links:
            - compte-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=compte
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    compte-mongodb:
        extends:
            file: mongodb.yml
            service: compte-mongodb
