version: '2'
services:
    compte-mongodb:
        container_name: compte-mongodb
        image: mongo:3.3.5
        ports:
            - "27017:27017"
        # volumes:
        #     - ~/volumes/jhipster/compte/mongodb/:/data/db/
